services:
  auth-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_AUTH}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - hammerx-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB_AUTH"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./backend/auth-service:/app
    networks:
      - hammerx-net

  lot-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_LOT}
    volumes:
      - lot_db_data:/var/lib/postgresql/data
    networks:
      - hammerx-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB_LOT"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  lot-service:
    build:
      context: ./backend/lot-service
      dockerfile: Dockerfile
    container_name: lot-service
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      lot-db:
        condition: service_healthy
    volumes:
      - ./backend/lot-service:/app
    networks:
      - hammerx-net

volumes:
  auth_db_data:
  lot_db_data:

networks: 
  hammerx-net:
